INSERT INTO user (student_id,
                   password,
                   email,
                   nickname,
                   graduated,
                   contact,
                   is_executive,
                   github_id,
                   baekjoon_id,
                   created_at,
                   created_by,
                   modified_at,
                   modified_by)
VALUES ('20230001',
        '123123',
        'sample@email.com',
        'sampleNick',
        0,
        '010-1234-5678',
        0,
        'sampleGithub',
        'sampleBaekjoon',
        '2023-07-09 00:00:00',
        'admin',
        '2023-07-09 00:00:00',
        'admin');

